### ISSUE TITLE
Implement config to swap A/B and X/Y

### ISSUE THREAD

**Issue by BrianAllred** [moslevin/netstick-3ds#3]
Just tested using Hades via Steam/Proton and it worked perfectly! My only complaint is that, since A/B and X/Y are swapped compared to an Xbox controller, I was pushing B to confirm and A to go back, which messed with my brain a little.

Having a config option to swap the pairs of buttons would be awesome!

**Comment by moslevin** [comment]
Great suggestion!  I'll implement this in the next release.

**Comment by moslevin** [comment]
Implemented in master as of the v5 release.
